name:                fs-cached-operation
version:             0.1.0.0
github:              "fghibellini/fs-cached-operation"
license:             MIT
author:              "Filippo Ghibellini"
maintainer:          "f.ghibellini@gmail.com"
copyright:           "2020 Filippo Ghibellini"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/fs-cached-operation#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - text
  - aeson
  - directory
  - filepath

tests:
  fs-cached-operation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fs-cached-operation
